name: Brendan Ryan

url: https://brendanjryan.com

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "_compress_images_cache.yml"
  - "Makefile"
  - README.md

plugins:
  - jekyll-compress-images
  - jekyll-redirect-from

imageoptim:
  svgo: false

gdrive:
  sheet: "website books"
  cache_period: 5 minutes
